#!/usr/bin/python

import libtrash

def printTrashedFile(trashedfile) :
    print "%s %s" % (trashedfile.getDeletionTime(), trashedfile.getPath())

td = libtrash.getHomeTrashDirectory()
td.forEachTrashedFile(printTrashedFile)
