#!/usr/bin/python

from libtrash import TrashDirectory
import os

list = []
i = 0
for trashedfile in TrashDirectory.allTrashedFilesInDir(os.curdir) :
    list.append(trashedfile)
    print "%4d %s %s" % (i, trashedfile.getDeletionTime(), trashedfile.getPath())
    i += 1

if len(list) == 0 :
    print "No trashed files"
else :
    index=raw_input("What file to restore [0..%d]: " % (len(list)-1))
    if index == "" :
        print "Exiting"
    else :
        index = int(index)
        list[index].restore()
