[tox]
requires = virtualenv<20.22.0
envlist = py27, py310

[testenv:mypy]
deps =
    mypy
    types-six
    types-mock
    types-psutil
commands =
    mypy --python-version 3.10 trashcli
    mypy --python-version 3.14 trashcli
    
[testenv]
deps =
    -r requirements.txt
    -r requirements-dev.txt
commands =
    pytest {posargs}
