#!/bin/bash
set -xe

version="$(python setup.py --version)"
python setup.py sdist
pip install "dist/trash-cli-$version.tar.gz"

trash --version
trash-put --version
trash-list --version
trash-rm --version
trash-restore --version
trash-empty --version
