#!/usr/bin/env python
from __future__ import print_function

if __name__ == '__main__':
    import os
    import sys

    root = os.path.realpath(os.path.join(__file__, "..", ".."))
    sys.path.insert(0, root)
    from tests.support.tools.bump_main import main

    main()
