#!/bin/bash
set -euo pipefail
set -x

python -m venv .venv
export VIRTUAL_ENV="$(pwd)/.venv"
export PATH="$VIRTUAL_ENV/bin:$PATH"
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install tox

tox &&
    scripts/test-sdist &&
    scripts/check-types

