#!/bin/bash
SCRIPT_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

set -euo pipefail
set -x

python -m venv .venv
source .venv/bin/activate

"$SCRIPT_DIR/lib/install-python-requirements"
"$SCRIPT_DIR/lib/check-python-dep" tox

true &&
    scripts/py27/check-types &&
    scripts/check-types &&
    scripts/py27/test-sdist &&
    scripts/test-sdist &&
    scripts/py27/test &&
    tox &&
true

