#!/bin/bash
SCRIPT_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -euo pipefail

python -m pip install --upgrade pip
"$SCRIPT_DIR/lib/install-python-requirements"

python -m pytest "$@"
