#!/usr/bin/env python

if __name__ == '__main__':
    import os
    import sys

    root = os.path.realpath(os.path.join(__file__, "..", ".."))
    sys.path.insert(0, root)
    from tests.support.tools.set_dev_version import main

    main()
