#!/bin/bash
set -xe

pip install --upgrade pip
pip install --upgrade build
pip install --upgrade setuptools
version="$(python -c 'import setuptools; setuptools.setup()' --version)"
python -m build --sdist

pip install "dist/trash-cli-$version.tar.gz"

trash --version
trash-put --version
trash-list --version
trash-rm --version
trash-restore --version
trash-empty --version
