.\" Copyright (C) 2008 Steve Stalcup <vorian@ubuntu.com>
.\"
.\" This manual page is free software.  It is distributed under the
.\" terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This manual page is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this manual page; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
.\" USA
.\"
.TH "RESTORE-TRASH" "1" 

.SH "NAME"
restore-trash \- Restore for Command line trash utility.

.SH "SYNOPSIS"
.B restore-trash

.SH "DESCRIPTION"
.PP
Use for restore a trashed file or directory, in the original path.
This command is a part of trash-cli package that provides a command 
line interface trashcan utility compliant with the FreeDesktop.org 
Trash Specification.
It remembers the name, original path, deletion date, and permissions of
each trashed file.

.SH "EXAMPLES"
.nf
$ restore-trash
0 2007-08-30 12:36:00 /home/andrea/foo
1 2007-08-30 12:39:41 /home/andrea/bar
2 2007-08-30 12:39:41 /home/andrea/bar2
3 2007-08-30 12:39:41 /home/andrea/foo2
4 2007-08-30 12:39:41 /home/andrea/foo
What file to restore [0..4]: 4
$ ls foo
foo
.fi

.SH "BUGS"
Report bugs to http://code.google.com/p/trash-cli/issues

.SH "AUTHORS"
Trash was written by Andrea Francia
<andreafrancia@users.sourceforge.net>
and Einar Orn Olason <eoo@hi.is>.
This manual page was written by Steve Stalcup <vorian@ubuntu.com>.
Changes made by Massimo Cavalleri <submax@tiscalinet.it>.

.SH "SEE ALSO"
trash-put(1), trash-list(1), trash-empty(1), and the
FreeDesktop.org Trash Specification at 
http://www.ramendik.ru/docs/trashspec.html.
.br

Both are released under the \s-1GNU\s0 General Public License,
version 2 or later.
