.\" Copyright (C) 2008 Steve Stalcup <vorian@ubuntu.com>
.\"
.\" This manual page is free software.  It is distributed under the
.\" terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This manual page is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this manual page; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
.\" USA
.\"
.TH "TRASH" "1"

.SH "NAME"
trash \- Command line trash utility.

.SH "SYNOPSIS"
.B trash
.RI [ arguments ]
\&...

.SH "DESCRIPTION"
.PP
Trash-cli package provides a command line interface trashcan utility
compliant with the FreeDesktop.org Trash Specification.
It remembers the name, original path, deletion date, and permissions of
each trashed file.

.SH "ARGUMENTS"
.TP
Names of files or directory to move in the trashcan.

.SH "EXAMPLES"
.nf
$ cd /home/andrea/
$ touch foo bar
$ trash foo bar
.fi

.SH "BUGS"
Report bugs to http://code.google.com/p/trash-cli/issues

.SH "AUTHORS"
Trash was written by Andrea Francia
<andreafrancia@users.sourceforge.net>
and Einar Orn Olason <eoo@hi.is>.
This manual page was written by Steve Stalcup <vorian@ubuntu.com>.
Changes made by Massimo Cavalleri <submax@tiscalinet.it>.

.SH "SEE ALSO"
trash-list(1), trash-restore(1), trash-empty(1), and the
FreeDesktop.org Trash Specification at 
http://www.ramendik.ru/docs/trashspec.html.
.br

Both are released under the \s-1GNU\s0 General Public License, 
version 2 or later.
