.\" Copyright (C) 2008 Steve Stalcup <vorian@ubuntu.com>
.\"
.\" This manual page is free software.  It is distributed under the
.\" terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This manual page is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this manual page; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
.\" USA
.\"
.TH "TRASH-EMPTY" "1"

.SH "NAME"
trash-empty \- Empty for Command line trash utility.

.SH "SYNOPSIS"
.B trash-empty
.RI [ arguments ]

.SH "DESCRIPTION"
.PP
Remove for ever any trashed file and trashed directory.
This command is a part of trash-cli package that provides a command 
line interface trashcan utility compliant with the FreeDesktop.org 
Trash Specification.
It remembers the name, original path, deletion date, and permissions of
each trashed file.

.SH "ARGUMENTS"
.TP
To remove all trashed files, use 'emtpy-trash'.
.TP
To remove files that have been in the trash more than a given number of
days, use 'trash-empty x', 'x' representing the number of days.

.SH "EXAMPLES"
.nf
$ date
Tue Feb 19 20:26:52 CET 2008
$ trash-list
2008-02-19 20:11:34 /home/einar/today
2008-02-18 20:11:34 /home/einar/yesterday
2008-02-10 20:11:34 /home/einar/last_week
$ trash-empty 7
$ trash-list
2008-02-19 20:11:34 /home/einar/today
2008-02-18 20:11:34 /home/einar/yesterday
$ trash-empty 1
$ trash-list
2008-02-19 20:11:34 /home/einar/today
$ trash-empty 
$ trash-list
<none>
.fi

.SH "BUGS"
Report bugs to http://code.google.com/p/trash-cli/issues

.SH "AUTHORS"
Trash was written by Andrea Francia
<andreafrancia@users.sourceforge.net>
and Einar Orn Olason <eoo@hi.is>.
This manual page was written by Steve Stalcup <vorian@ubuntu.com>.
Changes made by Massimo Cavalleri <submax@tiscalinet.it>.

.SH "SEE ALSO"
trash-put(1), trash-restore(1), trash-list(1), and the
FreeDesktop.org Trash Specification at 
http://www.ramendik.ru/docs/trashspec.html.
.br

Both are released under the \s-1GNU\s0 General Public License, version 2 or
later.
